#//:chapter7 makefile
CPP = g++
OFLAG = -o
GFLAG = -g
Stash3: Stash3Test.cpp Stash3.cpp
	${CPP} ${OFLAG}Stash3 Stash3Test.cpp Stash3.cpp
debug_Stash3: Stash3Test.cpp Stash3.cpp
	${CPP} ${GFLAG} ${OFLAG}debug_Stash3 Stash3Test.cpp Stash3.cpp
