#//:chapter7 makefile
CPP = g++
OFLAG = -o
GFLAG = -g

Stash3: Stash3Test.cpp Stash3.cpp
	${CPP} ${OFLAG}Stash3 Stash3Test.cpp Stash3.cpp
debug_Stash3: Stash3Test.cpp Stash3.cpp
	${CPP} ${GFLAG} ${OFLAG}debug_Stash3 Stash3Test.cpp Stash3.cpp
UnionClass: UnionClass.cpp
	${CPP} ${OFLAG}UnionClass UnionClass.cpp
SuperVar: SuperBar.cpp 
	${CPP} ${OFLAG}SuperVar SuperBar.cpp
Men: MenTest.cpp Men.cpp
	${CPP} ${OFLAG}Men  MenTest.cpp Men.cpp
