CPP = g++
OFLAG = -o
DE_PATH = /home/gary-liu/c++_exe/

all: \
	Constructorl1\
	Stash2\
	DefineInitialize\
	Stack3

Constructorl1: Constructorl1_main.cpp Constructorl1.cpp
	$(CPP) $(OFLAG) $(DE_PATH)Constructorl1 \
 Constructorl1_main.cpp Constructorl1.cpp
Stash2: Stash2_test.cpp Stash2.cpp
	$(CPP) $(OFLAG) $(DE_PATH)Stash2 Stash2_test.cpp Stash2.cpp
DefineInitialize: DefineInitialize.cpp
	$(CPP) $(OFLAG) $(DE_PATH)DefineInitialize DefineInitialize.cpp
Stack3: Stack3Test.cpp Stack3.cpp
	$(CPP) $(OFLAG) $(DE_PATH)Stack3 Stack3Test.cpp Stack3.cpp
Multiarg: Multiarg.cpp	
	$(CPP) $(OFLAG) $(DE_PATH)Multiarg Multiarg.cpp
